name: Go Build and Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # go-build-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
      
  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: 1.23  

  #     - name: Configure Git for HTTPS
  #       run: |
  #         git config --global url."https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/".insteadOf "https://bitbucket.org/"

  #     - name: Go Build and Test
  #       run: |
  #         go version
  #         go mod tidy
  #         go vet -v
  #         go test -v

  qwiet-nextgen-scan:
    runs-on: ubuntu-latest
    container: shiftleft/core:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

#      - name: Configure Git for HTTPS
#        run: |
#          git config --global url."https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/".insteadOf "https://bitbucket.org/"

      - name: Qwiet.AI NextGen Scan
        run: |
          sl analyze --app "${GITHUB_REPOSITORY_OWNER}_${GITHUB_REPOSITORY#*/}" --verbose --cpg --go .

        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
